cdlib/zephir-services

zed-verify/audit.py, zed-verify/tests/test_audit.py
Hi @jsjiang ,
When you get a chance, please review the audit log fix. I've changed it so when there are no events, it passes auditing.
=> 15656 fix audit log

cid-minting/.gitignore, cid-minting/README.dm, cid-minting/cid_inquiry.py, cid-minting/config.py, cid-minting/config/minter_db.yml, cid-minting/config/ocns_leveldb.yml, cid-minting/database/README.md, cid-minting/database/create_cid_minting_store_db.sql, cid-minting/lib/utils.py, cid-minting/oclc_lookup.py, cid-minting/run_cid_inquiry.sh, cid-minting/sample_ocns.txt, cid-minting/tests/test_cid_inquiry.py, cid-minting/tests/test_cid_minting_store/setup_cid_minter_db.sql, cid-minting/tests/test_oclc_lookup.py, cid-minting/zephir_cluster_lookup.py
@cscollett 
Hi Charlie,
1. Made Python scripts executable with options and arguments using click and regular argvs.
2. Provided a Shell wrapper for cid_inquirey.py.
3. Removed environment key (dev/stg/prd) from the LevelDB and minter DB configurations as both will be on local server with persistence location in all environments. (I have decided to use SQLite for the minter DB)
4.  Added unit tests for the executable scripts.
5. Updated readme
Please take a look and let me know if you have questions.
Thank you
Jing
=> 15791 cid minting store

cid-minting/zephir_cluster_lookup.py
This is to exclude CID=0 from the SQL select statement. Can you take a look.
Thank you
Jing
=> exclude 0 from CID selections

scripts/check_cid_difference.py, scripts/prune_cid_inquiry_tmp_files.sh
prune_cid_inquiry_tmp_files.sh - clean up temporary files produced by cid_inquiry
check_cid_difference.py - compare CID differences from parallel testing CID minting
=> Add maintenance scripts

scripts/select_parallel_log.sh
I modified the grep command to exclude unneeded lines. Please review and let me know if you have quesitons.
Thank you
Jing
=> modified log entry selecting cmds

scripts/check_cid_difference.py, scripts/select_parallel_log.sh
I refactored the parallel log analysis tool:
* Changed a data field label from HTID to "Contribsys_ID"
* Added time (HHMMSS) to the report name
* Removed lines with "--" from the input data file
Please review and let me know if you have quesitons.
Thank you
Jing
=> 16961 refactor parallel runlog analysis tool

zephir-exports/cid_repo_status_cli.py
@jsjiang I added quotes to try to speed up the query on your advice. Let me know what you think.
=> Add quotes to CIDs to increase SQL performance

zephir-exports/cid_repo_status_cli.py, zephir-exports/shared_cli.py, zephir-exports/tests/test_cid_repo_status_cli.py, zephir-exports/zephir-export-refactor.py
Hi Jing,
This adds a test case for empty files, and also skips all querying if the file results in no CIDs. Empty files result in empty results, but will show that they are querying 0 CIDs.
=> Fix failure with empty files cid change files

marctools/output_zephir_records.py, marctools/zephir_db_utils.py
These are helper functions for selecting and outputting Zephir records.  Changes to the zephir_db_utils.py script are in Line 40 and line 116-121, which add a query and a function to select shadow record form the zephir_Records table by IDs.
The test_output_shadow_records() function in output_zephir_records.py is only for testing.
Please review and let me know if you have quesiton.
Thank you
Jing
=> output shadow records by htid

tact_project/tact_db_utils.py, tact_project/tact_transformer.py
Here are the changes:
1.    Added the "convert_row_to_record(output_row)" function to convert a row read in from a file to the database record format (a dict of fieldname and value pairs)
2. Call the insert_tact_publisher_reports(db_conn_str, [db_record]) function to insert a record to the tact database.
3. Removed not necessary return statements. As Python passes the reference of the row to the function, changes made to the row in the function can be seen outside of the function. So there is no need to return the same row object.
The database operation is handled in the tact_database.py module. I will review the functions there later to optimize database operations such as create only one database session/connection for the whole process.
Please let me know if you …
=> write data entries to database

cid-minting/config/cid_minting.yml
This is to change leveldb file paths. Please review.
Thank you
Jing
=> change leveldb paths

tact_project/acm_mapper.py, tact_project/cob_mapper.py, tact_project/csp_mapper.py, tact_project/cup_mapper.py, tact_project/elsevier_mapper.py, tact_project/plos_mapper.py, tact_project/springer_mapper.py, tact_project/tact_db_utils.py, tact_project/tact_transformer.py, tact_project/trs_mapper.py
Here are the two major changes:
1. Initiate the output row (a list) before mapping input data to output. 
* Changes to the tact_transformer.py file are in line 122-123, 452-485 
output_row = init_output_row()
mapping_function(row, output_row)
* The mapping_function for each mapper are changed accordingly.
2. Initiate a database object and use it through out the process. 
* added the init_database(db_connect_str) function 
* create a database object and pass it to the insert function:
insert_tact_publisher_reports(database, [db_record])
Please review and let me know if you have questions.
Thank you
Jing
=> 19151 refactor tact db code

tact_project/cup_mapper.py, tact_project/sql/create_publisher_reports_table.sql, tact_project/tact_transformer.py, tact_project/utils.py
Here are the changes:
1. Added function to check multiple DOIs in one data field.
2. Reject data entry if the DOI field contains multiple DOIs
3. Reject data entry if it has a duplicated DOI (appear in other row(s) in the input file)
4. Move data normalization function to the utils.py file
5. Reorganized file processing and created functions to
* read in data
* map and normalize data entries
* write data entries to files and databases 
* 
Please review and let me know if you have quesitons.
Thank you
Jing
=> 19159 validate doi

tact_project/read_write_tact_records_sample_code.py, tact_project/sql/create_publisher_reports_table.sql, tact_project/sql/create_transaction_log_table.sql, tact_project/tact_db_utils.py, tact_project/tact_transformer.py
1. Create the transaction_log table
2. Generate transaction logs and store them in the transaction_log table. The transaction status is in JSON format with 3 types:
* New record
* Updated record
* Rejected record
3. Create run report in JSON.
I can go through the code with you at our pair-programming.
Thank you
Jing
=> 19130 create transaction log

prepare_zephir_records/read_write_zephir_records.py, prepare_zephir_records/test_data/test_1_ia-coo-2_20220511.xml, prepare_zephir_records/test_data/test_1_ia-coo-2_20220511_err.xml.saved, prepare_zephir_records/test_data/test_1_ia-coo-2_20220511_output.xml.saved
This is the code I showed to you last Friday. It only contains the core function of read in and write out zephir records. It still needs work to complete the command line functionality that can process files from:
* one configuration stream
* all configuration streams
Plus workflow control logic to:
* select qualified files
* mark files as "processed"
* copy output to the zephir servers for Gobble
* etc.
Also it requires code to handle:
* Command line options
* logging
* error handling
Can this code be merged to the master branch in this status? Or we. branch out from this branch for adding new functionalities?
Please review and let me know how to proceed.
Thank you
Jing
=> init commit for read write zephir records

prepare_zephir_records/cid_minter/cid_inquiry.py, prepare_zephir_records/cid_minter/tests/test_cid_inquiry.py, prepare_zephir_records/cid_minter/tests/test_zephir_cluster_lookup.py, prepare_zephir_records/cid_minter/zephir_cluster_lookup.py
I reorganized the the zephir_cluster_lookup.py script. The functions and logic remain the same. The major change is to reorganize the database related functions in two classes: 
* Database class: for general database related operations such as connection, find all, insert, close, etc.
* ZephirDatabase class: derived from the Database class with Zephir specific operations.
The unit tests were updated accordingly based on the function organization changes. There is no logic change to the tests.
In stead of looking at the difference, it might be easier to look at the zephir_cluster_lookup.py script itself.
Let me know if you have questions. Thank you
Jing
=> 19691 create database library

prepare_zephir_records/cid_minter/cid_minter.py, prepare_zephir_records/cid_minter/local_cid_minter.py, prepare_zephir_records/cid_minter/tests/test_local_cid_minter.py, prepare_zephir_records/cid_minter/tests/test_zephir_cluster_lookup.py, prepare_zephir_records/cid_minter/zephir_cluster_lookup.py, prepare_zephir_records/run_cid_minter.py
@RvanB Hi Raiden,
1. Define the find_cid_by_htid function in zephir_cluster_lookup.py and complete unit tests
2. Reimplemented logging across modules
3. Changed input data format to JSON/dict. We will format IDs extracted from a MARC record in this way and then pass it to the cid minter.
4. Listed CID minting functions in CidMinter.mint_cid(). These are only place holders. The minting algorithm will be implemented soon in next sprint.
Please review and let me know if you have questions.
Thank you
Jing
=> 19860 record current cid

prepare_zephir_records/cid_minter/cid_minter.py, prepare_zephir_records/run_cid_minter.py
This is to complete the workflow for minting CID by OCNs including:
* finding current CID for a given item 
* finding CID in local minter by OCNs
* finding CID in Zephir by OCNs
* reporting errors
Please review and let me know if you have questions.
Thank you
Jing
=> 19862 retrieve cid from local minter

prepare_zephir_records/cid_minter/cid_inquiry_by_ocns.py, prepare_zephir_records/cid_minter/cid_minter.py, prepare_zephir_records/cid_minter/tests/test_cid_inquiry_by_ocns.py, prepare_zephir_records/cid_minter/zephir_cluster_lookup.py, prepare_zephir_records/run_cid_minter.py, prepare_zephir_records/test_data/test_ids.json
* defined function _find_cid_in_zephir_by_sysids(self, sysids): find CID by given local system IDs
* reorganized mint_cid: consolidated the "return assigned_cid" statement. Return the assigned CID at the end instead of returning at each subroutine for CID assignment.
* refactored convert_comma_separated_str_to_int_list(ocn_str): add code and test to handle None value 
* added IDs for testing into the test_ids.json file.
Please take a look and let me know if you have questions.
Thank you
Jing
=> 19865 assign cid by sysid

prepare_zephir_records/cid_minter/cid_minter.py, prepare_zephir_records/cid_minter/tests/test_zephir_cluster_lookup.py, prepare_zephir_records/cid_minter/tests/test_zephir_cluster_lookup/setup_zephir_test_db.sql, prepare_zephir_records/cid_minter/zephir_cluster_lookup.py, prepare_zephir_records/run_zephir_cluster_lookup.py
* Added the update function to the Database class
* Removed unused insert and update on duplicated key functions
* Defined the ZephirTables and CidMinterTable classes and the update the cid_minter table function
* Added unit tests
* Defined helper functions _cid_assigned and _cid_not_assigned_yet to make code easy to read
* Excluded  clusters with CID=0 from CID minting process
Please take a look and let me know if you have questions.
Thank you
Jing
=> 19962 assign new cid

prepare_zephir_records/cid_minter/cid_minter.py, prepare_zephir_records/cid_minter/local_cid_minter.py, prepare_zephir_records/cid_minter/tests/test_local_cid_minter.py, prepare_zephir_records/run_cid_minter.py, prepare_zephir_records/test_data/test_ids.json
@RvanB Hi Raiden,
Here are the changes:
* refactored the CidMinter class - removed IDs from class attribute; added parameter "ids" to the mint_cid function.
* added the update_local_minter function to the  run_cid_minter.py script - update ID minting results to the local minter
Please take a look and let me know if you have questions.
Thank you
Jing
=> write cid minting  results to local minter db

prepare_zephir_records/integration_tests/how_to_run_integration_test.md, prepare_zephir_records/integration_tests/prepare_zephir_db.sh, prepare_zephir_records/integration_tests/run_integration_tests.sh
I have made the change to have the SQL command get the parameters from a config file:
sql_config="zephir_devtst.config"
sql_cmd="mysql --defaults-file=${sql_config}"
The config file is not included in the repo. Please review.
Thank you
Jing
=> read mysql params from config file

prepare_zephir_records/sql_scripts/create_cid_minter_tmp_tbl.sql, prepare_zephir_records/sql_scripts/create_cid_minting_store_tbl.sql, prepare_zephir_records/sql_scripts/update_cid_minter_tmp.sql
I am adding two scripts for creating the cid_minter_tmp and cid_minting_store tables, one script for syncing the cid_minter_tmp with cid_minter.
Please review. Thank you
Jing
=> create new tables

prepare_zephir_records/assign_cid_to_zephir_records.py, prepare_zephir_records/cid_minter/cid_minter.py, prepare_zephir_records/cid_minter/tests/test_cid_minter.py, prepare_zephir_records/cid_minter/tests/test_zed_for_cid.py, prepare_zephir_records/cid_minter/zed_for_cid.py, prepare_zephir_records/config/cid_minting.yml, prepare_zephir_records/run_integration_tests.sh, prepare_zephir_records/zed_for_cid.py
* added prepare_zephir_records/cid_minter/zed_for_cid.py for CidZedEvent class
* Integrated the CidZedEvent class with the CidMinter class
* adjusted tests and configuration accordingly
* implemented a few zed events (pr0059, pr0212, pr0213, pr0090 and pr0091)
Please review and let me know if you have questions.
Thank you
Jing
=> 19970 develop zed core
